---
title: "Intro_report"
author: "Kevin Gilds, MPA"
date: "July 2, 2016"
output: html_document
---

# Introduction
The Get REAL! program is a statewide mentoring program facilitated by six Girl Scout Councils in Florida. The goal of the Get REAL! program is to help at-risk middle school girls achieve academic success by connecting them to caring mentors in the community. Girl Scout facilitators and mentors deliver the Get REAL! program which includes a literacy component, character building, educational enhancement experience, and community service.
The purpose of this report is to measure the program against the established set of performance measures to ensure program quality. Evidence obtained from the program both quantitative and qualitative provide strong confidence that the Get REAL! program is meeting program objectives and providing value to students. 

## Program Operation
Each Girl Scout Council collaborates with the school officials to identify girls that would benefit from the Get REAL! program. Referrals come to the Get REAL! staff from school personnel and appropriate referrals for Get REAL! are at-risk girls based on (but not limited to) one or more of the following criteria:

* Enrolled in the 6th to 8th grade

* Are one or more grade levels behind in school;

* Who scored at Level l or Level II in FCAT reading;

* Have high absenteeism, or high disciplinary referrals;

* Struggling socially/family problems.

Student recruitment activities included meeting with school officials, word of mouth recruitment, announcement at school assemblies, visiting after-school programs. The enrollment goal of the Get REAL! program was to serve  students by the end of the 4th Quarter.  The Girl Scouts Councils reached or did not reach their goal by serving .  Student enrollment data by Girl Scout Council are as follows:



## Attendance Data
Students in the program attended on a regular basis as evidenced by monthly attendance reports. Review of attendance data demonstrates that the Girl Scout Councils consistently served over girls a month.  The councils started the program year fast by serving over  girls in October.  From March through May, Girl Scout councils were serving on average over  girls a month. 

## Staff Quality
All program staff and mentors are personally interviewed, complete an Affidavit of Good Moral Character, submit to a reference check, and must satisfactorily pass a criminal background check in order to begin working with students. Upon successful completion of the application process, new staff and mentors receive training on the approved program curriculum, and safety standards. Trainings that must be completed by new staff and mentors include Girl Scouts 101, CPR/First Aid, Diversity, and Team Building.   
## Mentor Recruitment
The Girl Scout Councils recruited and trained a total  individuals to be mentors and the mentors logged at least  hours to assist students in the program. The goal of the Get REAL! program was to recruit enough mentors to maintain a 15-1 student-mentor relationship.  The councils were not able to meet the 15-1 ratio. There appears to be variation between councils and their success with mentors.  The range of mentors by council ranged from a high of  to a low of .  



## Program Components:
 The education literature has shown that students who are engaged in school achieve better educational outcomes such as higher grades and greater achievement on standardized tests. In contrast, students who are disengaged are at a higher risk for dropping out of school. Student engagement is multiple dimensional including behavioral engagement, emotional engagement, and cognitive engagement. Behavioral engagement consists a student's participation in school activities. Emotional engagement refers to the connections and interactions a student has with peers and teachers. Cognitive engagement refers to resilience and the hard work required to be successful at school (Fredricks et al., 2011).

The program components of the Get REAL! program address the multiple facets of student engagement through a literacy program, character building, educational enhancements and community service opportunities. Facilitators and mentors work together to establish relationships with at-risk students and provide opportunities for educational enhancement trips and community services. The program components and activities of the Councils will be discussed in this section.


### Literacy Component:

Girl Quote



The reading portion of the Get REAL! program uses the See Girls Read! curriculum, and girls read at least five books during the 30-session program. As part of the Girl Scout process, students are given input about what books they wish to read. Mentors facilitate discussion about the books the girls are reading, and participants read and write in their journal. The group discussions and writing activities help increase emotional and cognitive engagement in the students. Periodically the girls are encouraged to share their journals with their mentor and the mentor will respond to them. Journaling gives girls additional writing experience and helps establish connections with their mentor. 
	

Write in narrative

'
Insert Table: Question: I learned from the books we read this year 

### Character Building/Life Skills:

Girl Quote



Relationships and connections with peers and teachers plays a critical role in academic engagement for students (Fredricks et al., 2011). All Girl Scout councils utilize the modules "Being a Girl", "Friendship" and "Body Image" from the Girls Circle curriculum. The modules focus on self-esteem, social development and interpersonal relationships to help the students solidify relationships with themselves, peers, and teachers.


Educational Enhancements:
Girls in the Get REAL! program participate in educational enhancements that consists of out-of-school learning experiences which  include camp visits, legislative day and half-day trips to local educational facilities.  Examples of the educational enhancement opportunities offered to the students in the program this year include legislative days, educational programs at theme parks, financial literacy workshops, summer camp, college tours, and a STOMP performance.


Community Care Projects
An important part of Girl Scouting is community care projects to help girls identify what they can do to help their community. Each program group develops their own projects that is specific to their community. 
 

