---
title: "Council_Data_Export"
author: "Kevin Gilds, MPA"
date: '`r Sys.Date()`'
output: html_document
---

Run date: '`r Sys.Date()`'

```{r echo=FALSE}
library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(dplyr)
library(pander)
library(ggplot2)
library (ezknitr)

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")


### Make connection with database
girl <- dbReadTable(getReal_2016db, "girl_pre")

###Select the neeeded data for data entry status update
girl <- select(girl, council)
###Create and add column for status update
girl$dataSource <-"girl"

### Make connection with database
parent <-dbReadTable(getReal_2016db,"pre_parent")
###Select the neeeded data for data entry status update
parent1 <- select(parent,council)
###Create and add column for status update
parent1$dataSource <- "parent"

### Make connection with database
teacher <-dbReadTable(getReal_2016db, "pre_teacher")
###Select the neeeded data for data entry status update
teacher1 <-select(teacher,council)
###Create and add column for status update
teacher1$dataSource <- "teacher"

###Bind girl and parent objects to prepare for status report
girl_parent <- rbind(girl,parent1)

### Make connection with database
grades_q1 <- dbReadTable(getReal_2016db,"Q1_Absences")
###Select the neeeded data for data entry status update

q1_stats <- select(grades_q1,council.x)
###Change column name to make it match with other data sets
colnames (q1_stats) [1] <- "council"
###Create and add column for status update
q1_stats$dataSource <- "Q1"


### Add the teacher to binding for status report
add_teacher <- rbind(girl_parent, teacher1)


###Findal addition to create data frame for status report
survey_status <- rbind(add_teacher, q1_stats)

### Read the pre girl survey for reference down stream
girl_survey_dupes <-dbReadTable(getReal_2016db, "girl_pre_duplicates")
### Read the pre girl survey for reference down stream
parent_survey_dupes <-dbReadTable(getReal_2016db, "pre_parent_duplicate")
### Read the pre girl survey for reference down stream
q1_dupes <-dbReadTable(getReal_2016db, "Q1_duplicates")

### Reade the girl_pre_survey database for analysis. 
outcomes <- dbReadTable(getReal_2016db, "girl_pre")
###Select the variables of interest from the pre_survey
outcomes <- select(outcomes, girlCode, school, council, hr.avg, am.avg, ae.avg)

#### Read q1_reading data from database for analysis
q1_reading <-dbReadTable(getReal_2016db, "Q1_reading")

### Read q1_langarts data from database for analysis
q1_langarts <-dbReadTable(getReal_2016db,"Q1_lang")

###Read q1_absences data from database for analysis
q1_absences <-dbReadTable(getReal_2016db, "Q1_Absences")

###Read q2_absences data from database for analysis
q1_suspensions <- dbReadTable(getReal_2016db, "Q1_Suspensions")


###Read academic data from database for file explort
academic_data <- dbReadTable(getReal_2016db, "academic_data")



```


```{r}

### Read girl survey data
girl_tbl <- select(outcomes, council, school, girlCode, hr.avg, ae.avg,am.avg )

### create table to see how many to be expected
girl_tbl_test <- with(girl_tbl, table(council))

###Show output
girl_tbl_test

###Read girl survey dupes
girl_survey_dupes1 <- select(girl_survey_dupes,council, school, girlCode)

###Create table to see how many to be expected
dupe_test <-with(girl_survey_dupes, table(council))

###Create output
dupe_test

###Create table to show many councils per. 
with(academic_data,table(council))



```

### Save All to main council folder
```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data")

write.csv(girl_survey_dupes, "girl_survey_dupes.csv", row.names = FALSE)
write.csv(parent_survey_dupes, "parent_survey_dupes.csv", row.names = FALSE)
write.csv(q1_dupes, "q1_dupes.csv", row.names = FALSE)

```



### Girl Survey File Function
```{r}

girl_file <- function(x) {
    girl_tbl <- filter(girl_tbl, council == x)
    write.csv (girl_tbl, file="girl_survey.csv", row.names=FALSE)
    
    
}



```


### Dupe Girl File Functions
```{r}

 

girl_dupe_file <- function(x) {
    girl_survey_dupes <- filter(girl_survey_dupes, council == x)
    write.csv(girl_survey_dupes, "girl_survey_dupes.csv", row.names=FALSE)
}

```


### Grade Function

```{r}
grade_file <-function(x) {
    academic_data <-filter(academic_data,council == x)
    write.csv(academic_data, "student_academics.csv", row.names = FALSE)
}

```

### Grade Dupe Function

```{r}

grade_dupe_file <- function(x) {
    q1_dupes <- filter(q1_dupes, council == x)
    write.csv(q1_dupes, "q1_dupes.csv", row.names = FALSE)
}

```


### Parent Survey

```{r}
pre_parent <- function(x){
    pre_parent <-filter(parent, council == x)
    write.csv(pre_parent, "pre_parent_survey.csv", row.names = FALSE)
}

```

### Pre Parent dupe

```{r}

pre_parent_dupe_file <- function(x) {
    pre_parent_dupe <- filter(parent_survey_dupes, council == x)
    write.csv(pre_parent_dupe, "pre_parent_dupes.csv", row.names = FALSE)
}

```

### Pre Teacher Survey
```{r}
pre_teacher_file <- function(x) {
    pre_teacher <- filter(teacher, council == x)
    write.csv(pre_teacher, "pre_teacher.csv", row.names = FALSE)
}

```



### Citrus Council

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/citrus_council")

girl_file("Citrus Council")

girl_dupe_file("Citrus Council")

grade_file("Citrus Council")

grade_dupe_file("Citrus Council")

pre_parent("Citrus Council")

pre_parent_dupe_file("Citrus Council")

pre_teacher_file("Citrus Council")

```




### Southeast Council
```{r}

setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/southeast")


girl_file("Southeast Council")



girl_dupe_file("Southeast Council")

grade_file("Southeast Council")

grade_dupe_file("Southeast Counil")

pre_parent("Southeast Council")

pre_parent_dupe_file("Southeast Council")

pre_teacher_file("Southeast Council")

```

### Gateway Council

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/gateway_council")

girl_file("Gateway Council")

girl_dupe_file("Gateway Council")

grade_file("Gateway Council")

grade_dupe_file("Gateway Council")

pre_parent("Gateway Council")

pre_parent_dupe_file("Gateway Council")

pre_teacher_file("Gateway council")

```

### Tropical Council

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/tropical_council")

girl_file("Tropical Council")

girl_dupe_file("Tropical Council")

grade_file("Tropical Council")

grade_dupe_file("Tropical Council")

pre_parent("Tropical Council")

pre_parent_dupe_file("Tropical Council")

pre_teacher_file("Tropical Council")

```

### Panhandle Council

```{r}

setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/panhandle_council")

girl_file("Panhandle Council")


girl_dupe_file("Panhandle Council")

grade_file("Panhandle Council")

grade_dupe_file("Panhandle Council")

pre_parent("Panhandle Council")

pre_parent_dupe_file("Panhandle Council")

pre_teacher_file("Panhandle Council")

```


### West Central Council

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Council_data/west_central_council")

girl_file("West Central Council")

girl_dupe_file("West Central Council")

grade_file("West Central Council")

grade_dupe_file("West Central Council")

pre_parent("West Central Council")

pre_parent_dupe_file("West Central Council")

pre_teacher_file("West Central Council")

```

