---
title: "Q1grades_dm"
author: "Kevin Gilds"
date: '`r Sys.Date()`'
output: html_document
---

### Intro this section needs to be updated.  today's data is 04/01/2016

```{r}

#### Load the Libraries
library(dplyr)
library(reshape2)
library(pander)
library(sqldf)


### Locate file to read from
setwd("C:/Users/kevin/Dropbox/GetReal/Data/2015-2016/March 2016")

### read the data into R
grades <- read.csv('q1Grades03092016.csv', skip = 1, na.strings="")


```

```{r}

### Demo Variables
colnames (grades) [7] <- "council"
colnames (grades) [8] <- "girlCode"
colnames (grades) [9] <- "schoolName"
colnames (grades) [10] <- "dateEnrolled"

#### Behavioral Variables
colnames (grades) [12] <- "unexcusedAbs"
colnames (grades) [13] <- "excusedAbs"
colnames (grades) [14] <- "inSchoolSusp"
colnames (grades) [15] <- "outofSchoolSusp"
colnames (grades) [16] <- "expelled"


### Reading Courses

colnames (grades) [19] <- "mjIntensRead"
colnames (grades) [20] <- "mjIntenseReadCareerPlaning"
colnames (grades) [21] <- "mjRead1"
colnames (grades) [22] <- "mjRead1Adv"
colnames (grades) [23] <- "mjRead2"
colnames (grades) [24] <- "mjRead2Adv"
colnames (grades) [25] <- "mjRead3"
colnames (grades) [26] <- "mjRead3Adv"
colnames (grades) [27] <- "mjDelaESOLRead"
colnames (grades) [28] <- "readFree1"
colnames (grades) [29] <- "readFree2"


### Lang Arts Courses

colnames (grades) [31] <- "mjLangArts1ESOL"
colnames (grades) [32] <- "mjLangArts2ESOL"
colnames (grades) [33] <- "mjLangArts3ESOL"
colnames (grades) [34] <- "mjDevelpmentalESOL"


colnames (grades) [35] <- "mjLangArts1"
colnames (grades) [36] <-"mjlangsArts1Adv"
colnames (grades) [37] <-"mjLangArts2"
colnames (grades) [38] <- "mjLangArts2Adv" 
colnames (grades) [39] <- "mjLangArts3"
colnames (grades) [40] <- "mjLangArts3Adv"


colnames (grades) [41] <- "mjEng2Cambsec2"
colnames (grades) [42] <- "mjIBLangArts1"
colnames (grades) [43] <- "mjEng2CamSec1"
colnames (grades) [44] <- "mjIBLangArts3"
colnames (grades) [45] <- "mjIBLangArts2"
colnames (grades) [46] <- "mjEng3Cambsec3"


colnames (grades) [47] <- "mjIntensLangArts"
colnames (grades) [48] <- "freeLang1"
colnames (grades) [49] <- "freeLang2"
colnames (grades) [50] <- "mjLangTran"


```


```{r}
################Finished Data Entry####################################33

### Eliminate uncompleted data entry
gradesq1 <- filter(grades, Finished == 1)


```

```{r}

#######################Fix Factors ###################################

### Make all girCode to upper case for matching
gradesq1$girlCode <- toupper(gradesq1$girlCode)

### Make sure R does not make this a factor variable
gradesq1$council <- as.character(gradesq1$council)

### Make sure R does not make this a factor variable 
gradesq1$girlCode <- as.character(gradesq1$girlCode)



```


```{r}


##############################Subset Duplicate Values##################
### find the duplicates
q1Dupes <-duplicated(gradesq1$girlCode) | duplicated(gradesq1$girlCode, fromLast=TRUE)

### Subset the duplicates
q1Dupes <-gradesq1[q1Dupes, ]






```

```{r}
##################Duplicates#########################################

### Find the unique girlCodes and subset them
gradesUnique <- gradesq1 [!(duplicated(gradesq1$girlCode) | duplicated(gradesq1$girlCode, fromLast = TRUE)), ]

dim(gradesUnique)



```


```{r}

### Change council names to be consistent wiht how they displayed with the surveys
gradesUnique$council <-sub("Girl Scouts of the Gateway Council", "Gateway Council", fixed=TRUE, gradesUnique$council)

gradesUnique$council <-sub("Girl Scouts of Citrus Council", "Citrus Council", fixed=TRUE, gradesUnique$council)

gradesUnique$council <-sub("Girl Scouts of Southeast Florida", "Southeast Council", fixed=TRUE, gradesUnique$council)

gradesUnique$council <-sub("Girl Scout Council of Tropical Florida", "Tropical Council", fixed = TRUE, gradesUnique$council)

gradesUnique$council <-sub("Girl Scouts of West Central Florida", "West Central Council", fixed = TRUE, gradesUnique$council)

gradesUnique$council <-sub("Girl Scout Council of the Panhandle", "Panhandle Council", fixed = TRUE, gradesUnique$council)



```


```{r}

```{r}
###############Reading Clean Up###############################################################

### Select data of interest
q1Reading <- select(gradesUnique, 7,8, 19:27)




```

