---
title: "Girl Report Trends"
author: "Kevin Gilds"
date: "November 28, 2015"
output: html_document
---

```{r}

setwd("C:/Users/kevin/Dropbox/GetReal/Reports/MY-2014-2015/Summ Evaluation Report/data")
library(sqldf)
library(reshape2)
library(dplyr)
library(ggplot2)
library(pander)
library(psych)
getRealdb<- dbConnect(SQLite(), dbname="data_Final_GetReal_2014_2015.sqlite")


```


### 2014-2015 Survey Data
```{r}

all_Tables <- dbListTables(getRealdb)

all_Tables

pre_survey_2014 <- dbReadTable(getRealdb, "pre_girl_survey")

dim(pre_survey_2014)

post_survey_MY1415 <- dbReadTable(getRealdb, "post_girl_survey")

dim(post_survey_MY1415)

```

### Survey Data from 2015 School year

```{r}
setwd("C:/Users/kevin/Dropbox/GetReal/Data/2015-2016/December 2015")

pre_survey_2015 <- readRDS("girl_survey_12202015.rds")

dim(pre_survey_2015)

```


### Match Pre Surveys
```{r}

pre_merge <- inner_join (pre_survey_2014, pre_survey_2015, by = "girlCode", Copy=FALSE)

dim(pre_merge)

#x=2014, y=2015


```



### Match Post Survey

```{r}

post_merge <- inner_join(post_survey_MY1415, pre_survey_2015, by = "girlCode", Copy=FALSE)

dim(post_merge)


```

### Match Pre, Post, Pre

```{r}

all_merge <- inner_join(post_merge, pre_merge, by = "girlCode", Copy=FALSE)

dim(all_merge)



```


### Outcomes, Pre, Post, Pre

```{r}

outcomes_all_merge <- select(all_merge, girlCode, StartDate.x.x, hr.avg.x.x, ae.avg.x.x, am.avg.x.x, StartDate.x.y, hr.avg.x.y, ae.avg.x.y, am.avg.x.y, StartDate.y.y, hr.avg.y.y, ae.avg.y.y, am.avg.y.y)

outcomes_all_merge


```



```{r}

hr_all <- select(outcomes_all_merge, girlCode, StartDate.x.x, hr.avg.x.x,StartDate.x.y, hr.avg.x.y, StartDate.y.y, hr.avg.y.y)


###Change variable names for ease of use.
colnames(hr_all) [3] <- "hr_point2"
colnames(hr_all) [5] <- "hr_point1"
colnames(hr_all) [7] <- "hr_point3"
colnames(hr_all) [2] <- "Time_2"
colnames(hr_all) [4] <- "Time_1"
colnames(hr_all) [6] <- "Time_3"


hr_point_1 <- select(hr_all, hr_point1)

time_1 <- "Time_1"

hr_point_1 <- cbind(hr_point_1, time_1)

head(hr_point_1)

hr_point_2 <-select(hr_all, hr_point2)

time_2 <- ("Time_2")

hr_point_2 <- cbind(hr_point_2, time_2)

head(hr_point_2)

hr_1_hr_2 <- cbind(hr_point_1, hr_point_2)

head(hr_1_hr_2)

melt_hr <- melt(hr_1_hr_2)

head(melt_hr)

tail(melt_hr, n=20)

summary(melt_hr)

class(melt_hr$variable)



cor(hr_all$hr_point1, hr_all$hr_point2)


####Summarize hr time averages
describe(hr_all$hr_point1)
describe(hr_all$hr_point2)
describe(hr_all$hr_point3)

#####Difference between point 3 and point 1.
hr_diff <- (hr_all$hr_point3 - hr_all$hr_point1)

hr_diff

table(hr_diff <=0)


###Summarize Difference 
describe(hr_diff)

### Plot difference
plot(hr_diff)
abline(h=0, col='red')


###Bind hr_diff to hr_all

hr_all1 <- cbind(hr_all, hr_diff)



hr_achieved <- with(hr_all1, table(hr_point3 >=4.45))

hr_achieved






#### Outcome Post Merge



outcomes <- select(post_merge, girlCode, StartDate.x, hr.avg.x, ae.avg.x, am.avg.x, StartDate.y, hr.avg.y, ae.avg.y, am.avg.y)

dim(outcomes)

head(outcomes)

```

### Healthy Relationship Outcome Tables


```{r}

#########Outcome Table#################3

###Final Add raw increase with maintained high achievement.




##################Raw Increase########################3
hr_increase <-filter(hr_all1, hr_diff > 0)

hr_increase_tbl <- with(hr_all1, table(hr_diff >0))

pander(hr_increase_tbl)



dim(hr_increase)




###########################Maintain High Level but did not increase Outcome Score###########


hr_maintain <-filter(hr_all1, hr_point3 >=4.45 & hr_diff <=0)

hr_maintain

hr_maintain_tbl <-with(hr_all1,table(hr_point3 >=4.45 & hr_diff <=0))

pander(hr_maintain_tbl)




######################Not achieving to achieving

hr_success <- with(hr_all1, table(hr_point1 <4.45 & hr_point3 >=4.45))

hr_success


```







### Pre 2014-Pre 2015Healthy Relationships

```{r set up health relationship data, }
####################Pair down date frame into the Outcomes that we are interested in#########
hr <- select(pre_merge, Time.x, council.x, girlCode, hr.avg.x, hr.avg.y)


#########################Match the completed cases################################
hr1<-hr %>% filter(complete.cases(hr)) 


############################Calculate diff between post score and pre score##########
diffhr <- (hr1$hr.avg.x- hr1$hr.avg.y)

###################Bind to dataframe##########################################
hr1<-cbind(hr1, diffhr)


```



```{r hr test, echo=FALSE}
######################Basic Analsis T-tests############################################

hr2 <- select(hr1, Time.x, girlCode,hr.avg.x, hr.avg.y)

t.test(hr2$hr.avg.x, hr2$hr.avg.y, paired=TRUE)

```



```{r hr graphs, echo=FALSE}

####Need to fix the scales. 
hrhist<-
par(mfrow=c(1,2))

hist(hr2$hr.avg.y, col="blue", main="Pre:Outcome Distribution", xlab="Healthy Relationship Outcome Scores")
abline(v=4.45, col="red")
hist(hr2$hr.avg.x, col="blue", main="Post:Outcome Distribution", xlab="Healthy Relationship Outcome Scores" )
abline(v=4.45, col="red")



```


### Tests

```{r wilcox, echo=FALSE}

boxplot(hr2$hr.avg.y, hr2$hr.avg.x)
wilcox.test(hr2$hr.avg.y, hr2$hr.avg.x, "less",paired=TRUE)



```




### Pre Survey Data and Graphs

```{r fig.width=15}

ggplot(hr1, aes(hr.avg.y >=4.45)) + geom_bar(stats="identitiy", fill="blue", width = .5) + labs(x="Achieving at High Level", title = "Pre: Healthy Relationships")

ggplot(hr, aes(hr.avg.y >=4.45, fill= council.x)) + geom_bar(stats = "identity") + facet_grid(~council.x) + labs(x = "Achieving at High Level", title = "Pre: Healthy Relationships by Council")


###########Pre Survey Results

hr_table_pre <- with(hr1,table(hr.avg.y >=4.45))

pander(hr_table_pre, style = "multiline")


#########Pre by council#################

hr_table_pre_council <-with(hr1,table(council.x, hr.avg.y >=4.45))

pander(hr_table_pre_council, style = "multiline")

##########By Percents##################


```





