---
title: "Attributional"
author: "Kevin Gilds, MPA"
date: "May 22, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sqldf)
library(dplyr)
library(pander)
library(ggplot2)
library(knitr)
library(likert)



setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")



attr <-dbReadTable(getReal_2016db, "girl_post")




```


```{r}

data(pisaitems)

items28 <- pisaitems[, substr(names(pisaitems), 1, 5) == "ST24Q"]
head(items28)

```



```{r}

attr_1 <- select(attr, 46:49)


names(attr_1)

str(attr_1)

attr_1 <- lapply(attr_1, factor, levels=c("Don't Know/Prefer Not to say","Strongly Disagree", "Disagree", "Disagree a little","Agree a little", "Agree", "Strongly Agree" ), ordered=TRUE)

str(attr_1)

class(attr_1)

attr_tbl <- lapply(attr_1,table)

pander(attr_tbl)




```





```{r fig.height=7,fig.width=15, echo=FALSE, warning=FALSE}

attr_1 <-as.data.frame(attr_1)

attr_likert <- likert(attr_1)





likert.heat.plot(attr_likert)


plot(attr_likert)


```


```{r}




```

