---
title: "funwithfunctions"
author: "Kevin Gilds, MPA"
date: '`r Sys.Date()`'
output: html_document
---


The data below is from data pulled in December 2015 and the basis for the Formative Evaluation Report. 

```{r r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=5, fig.path='Figs/',
                       warning=FALSE, message=FALSE, echo=FALSE)




```



```{r echo=FALSE}
library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(dplyr)
library(pander)
library(ggplot2)
library (ezknitr)
library(formattable)

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")


### Make connection with database
girl <- dbReadTable(getReal_2016db, "girl_pre")

###Select the neeeded data for data entry status update
girl <- select(girl, council)
###Create and add column for status update
girl$dataSource <-"girl"

### Make connection with database
parent <-dbReadTable(getReal_2016db,"pre_parent")
###Select the neeeded data for data entry status update
parent <- select(parent,council)
###Create and add column for status update
parent$dataSource <- "parent"

### Make connection with database
teacher <-dbReadTable(getReal_2016db, "pre_teacher")
###Select the neeeded data for data entry status update
teacher <-select(teacher,council)
###Create and add column for status update
teacher$dataSource <- "teacher"

###Bind girl and parent objects to prepare for status report
girl_parent <- rbind(girl,parent)

### Make connection with database
grades_q1 <- dbReadTable(getReal_2016db,"Q1_Absences")
###Select the neeeded data for data entry status update

q1_stats <- select(grades_q1,council.x)
###Change column name to make it match with other data sets
colnames (q1_stats) [1] <- "council"
###Create and add column for status update
q1_stats$dataSource <- "Q1"


### Add the teacher to binding for status report
add_teacher <- rbind(girl_parent, teacher)


###Findal addition to create data frame for status report
survey_status <- rbind(add_teacher, q1_stats)

### Read the pre girl survey for reference down stream
girl_survey_dupes <-dbReadTable(getReal_2016db, "girl_pre_duplicates")
### Read the pre girl survey for reference down stream
parent_survey_dupes <-dbReadTable(getReal_2016db, "pre_parent_duplicate")
### Read the pre girl survey for reference down stream
q1_dupes <-dbReadTable(getReal_2016db, "Q1_duplicates")

### Reade the girl_pre_survey database for analysis. 
outcomes <- dbReadTable(getReal_2016db, "girl_pre")
###Select the variables of interest from the pre_survey
outcomes <- select(outcomes, girlCode, council, hr.avg, am.avg, ae.avg)


q1_reading <-dbReadTable(getReal_2016db, "Q1_reading")
q1_langarts <-dbReadTable(getReal_2016db,"Q1_lang")
q1_absences <-dbReadTable(getReal_2016db, "Q1_Absences")
q1_suspensions <- dbReadTable(getReal_2016db, "Q1_Suspensions")


```


```{r}

hr <- function(){
    hr_tbl <- with(outcomes,table(hr.avg >=4.45))
    pander(hr_tbl)
    
}
```


```{r}

hr()

```


```{r}

hr_percent <- function() {
    hr_tbl <- with(outcomes,table(hr.avg >=4.45))
    hr_tbl_p <- prop.table(hr_tbl)
    hr_tbl_p <- round(hr_tbl_p*100,2)
    pander(hr_tbl_p)
}

```

```{r}

hr_percent()

```


```{r}
ae <- function() {
    ae_tbl <-with(outcomes,table(ae.avg >=4.5))
    pander(ae_tbl)
    
}

```


```{r}
ae()
```


```{r}
ae_percent <-function() {
    ae_tbl <-with(outcomes,table(ae.avg >=4.5))
    ae_p <-prop.table(ae_tbl)
    ae_p <-round(ae_p*100,2)
    pander(ae_p)
}

```


```{r}

ae_percent()

```


```{r}

am <- function() {
    am_tbl <-with(outcomes,table(am.avg >=4.8))
    pander(am_tbl)
}

```

```{r}
am()





```{r}

```



```{r}

am_percent <-function() {
    am_table <-with(outcomes,table(am.avg >=4.8))
    am_p <-prop.table(am_table)
    am_p <-round(am_p*100,2)
    pander(am_p)
}

```


```{r}

am_percent()

```


```{r}



```













