---
title: "grade_analysis_2"
author: "Kevin Gilds, MPA"
date: '`r Sys.Date()`'
output: html_document
---



```{r}

library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")

library(dplyr)
library(dplyr)
library(pander)
library(ggplot2)
library (ezknitr)

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")


q1_reading <-dbReadTable(getReal_2016db, "Q1_reading")
q1_langarts <-dbReadTable(getReal_2016db,"Q1_lang")
q1_absences <-dbReadTable(getReal_2016db, "Q1_Absences")
q1_suspensions <- dbReadTable(getReal_2016db, "Q1_Suspensions")
q2_reading <- dbReadTable(getReal_2016db, "Q2_reading")
q2_langarts <-dbReadTable(getReal_2016db, "Q2_lang")
q2_absences <-dbReadTable(getReal_2016db, "Q2_Absences")
q2_suspensions <-dbReadTable(getReal_2016db, "Q2_Suspensions")



```



# Reading Data

```{r}
reading <-inner_join(q1_reading, q2_reading, by="girlCode")

dim(reading)
head(reading)

reading_1 <- reading %>%
    select(girlCode,council.x, reading_pts, reading_pts2)

head(reading_1)


reading_q2q1 <- reading_1 %>%
    mutate(reading_pt_diff = reading_pts2 - reading_pts)





dim(reading_q2q1)


    


```

### Reading Grade Change

```{r}



reading_change <- table(reading_q2q1$reading_pt_diff, reading_q2q1$reading_pts2)


reading_change_1 <- with(reading_q2q1, table(reading_pts2 >=2, reading_pt_diff >=0))
pander(reading_change_1)

pander(reading_change)


plot(reading_change)
```






### Reading Stats

```{r}

with(reading_q2q1,table(reading_pts))

with(reading_q2q1,table(reading_pts2))


gpa_reading_1 <- mean(reading_q2q1$reading_pts)
hist(reading_q2q1$reading_pts)
gpa_reading_2 <- mean(reading_q2q1$reading_pts2)
hist(reading_q2q1$reading_pts2)

reading_gpa_change <- (gpa_reading_2 - gpa_reading_1)

reading_gpa_change

mean(reading_q2q1$reading_pt_diff)

```




# Language Arts Grades

```{r}

langarts <- inner_join(q1_langarts, q2_langarts, by="girlCode")

dim(langarts)

langarts_1 <- langarts %>%
    select(girlCode, council.x, lang_pts, lang_pts2)

langarts_q2q1 <- langarts_1 %>%
    mutate(pt_diff = lang_pts2 - lang_pts)



```


## Language Arts Grade Change

```{r}
lang_change <- with(langarts_q2q1, table(pt_diff, lang_pts2))

pander(lang_change)

lang_change_1 <- with(langarts_q2q1, table(lang_pts >=2, pt_diff >=0))

pander(lang_change_1)


plot(lang_change)

```

### Lang Arts Grade Stats
```{r}
with(langarts_q2q1,table(lang_pts))
langpts_density <- density(langarts_q2q1$lang_pts)
hist(langarts_q2q1$lang_pts, freq = FALSE)
lines(langpts_density)

with(langarts_q2q1,table(lang_pts2))
langpts2_density <- density(langarts_q2q1$lang_pts2)
hist(langarts_q2q1$lang_pts2, freq = FALSE)
lines(langpts2_density)

mean(langarts_q2q1$pt_diff)

```


# Absences
```{r}

absences <- inner_join(q1_absences, q2_absences, by="girlCode")

dim(absences)

head(absences)

absences_1 <- absences %>%
    select(girlCode, council.x.x, sum_abs.x, sum_abs.y) 
    
absences_q2q1 <- absences_1 %>%
    mutate(abs_diff = sum_abs.y - sum_abs.x)





```

## Absences Change
```{r}

absences_change <- with(absences_q2q1, table(abs_diff,sum_abs.y))

pander(absences_change)

absences_change_1 <-with(absences_q2q1,table(abs_diff <0))

absences_change_2 <-with(absences_q2q1,table(abs_diff ==0, sum_abs.y == 0))

pander(absences_change_2)


pander(absences_change_1)

plot(absences_change)

```



```{r}

suspsensions <- inner_join(q1_suspensions, q2_suspensions, by="girlCode")


head(suspsensions)

suspsensions_1 <- suspsensions %>%
    select(girlCode, council.y.x, susp_sum.x, susp_sum.y)

suspensions_q2q1 <- suspsensions_1 %>%
    mutate(susp_diff = susp_sum.y - susp_sum.x)




```


## Suspensions Changes

```{r}

suspensions_change <- with(suspensions_q2q1,table(susp_diff, susp_sum.y))

pander(suspensions_change)

suspensions_change_1 <- with(suspensions_q2q1,table(susp_diff < 0))

pander(suspensions_change_1)


suspensions_change_2 <- with(suspensions_q2q1,table(susp_diff ==0, susp_sum.y==0))

pander(suspensions_change_2)




plot(suspensions_change)
```
