---
title: "Status Report"
author: "Kevin Gilds, MPA"
date: '`r Sys.Date()`'
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r echo=FALSE, message=FALSE, warning= FALSE}
library(sqldf)
setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")

getReal_2016db<- dbConnect(SQLite(), dbname="outcome_history.sqlite")


```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(dplyr)
library(pander)
library(ggplot2)

setwd("C:/Users/kevin/Dropbox/GetReal/Data/sqlite")


### Make connection with database
pre_girl <- dbReadTable(getReal_2016db, "girl_pre")

###Select the neeeded data for data entry status update
pre_girl <- select(pre_girl, council)
###Create and add column for status update



pre_girl$dataSource <-"Pre-Student"

###Post Girl

post_girl <-dbReadTable(getReal_2016db, "girl_post") #read table

post_girl <- post_girl %>%
    select(council) %>%  #select variables
    mutate("dataSource" = "Post Student") #add new column



### Make connection with database
pre_parent <-dbReadTable(getReal_2016db,"pre_parent")
###Select the neeeded data for data entry status update
pre_parent <- select(pre_parent,council)
###Create and add column for status update
pre_parent$dataSource <- "Pre-Parent"


###Post Parent

post_parent <-dbReadTable(getReal_2016db, "post_parent") #read table 

post_parent <- post_parent %>%
    select(council) %>%  #select columns
    mutate("dataSource"= "Post Parent") #add colummns


### Make connection with database
pre_teacher <-dbReadTable(getReal_2016db, "pre_teacher")
###Select the neeeded data for data entry status update
pre_teacher <-select(pre_teacher,council)
###Create and add column for status update
pre_teacher$dataSource <- "Pre Teacher"


#Post Teacher

post_teacher <-dbReadTable(getReal_2016db, "post_teacher") #read table from database

post_teacher <- post_teacher %>%
    select(council) %>%
    mutate("dataSource"= "Post Teacher")



##### Geyset counts of Pre and Post Surveys
girl <- nrow(pre_girl) + nrow(post_girl)

class(girl)
parent <- nrow(pre_parent) + nrow(post_parent)
teacher <- nrow(pre_teacher) + nrow(post_teacher)


Data_Entry<- c(girl, parent, teacher)

Data_Source <- c("Student", "Parent", "Teacher")

total_survey_count <- data.frame(Data_Source, Data_Entry)

total_survey_count






###Bind girl and parent objects to prepare for status report
girl_parent <- rbind(pre_girl,pre_parent)


### Add the teacher to binding for status report
survey_status <- rbind(girl_parent, pre_teacher)

survey_status <- rbind(survey_status, post_girl)

survey_status <- rbind(survey_status, post_parent)

survey_status <- rbind(survey_status, post_teacher)




### Make connection with database
grades_q1 <- dbReadTable(getReal_2016db,"Q1_Absences")
###Select the neeeded data for data entry status update

q1_stats <- select(grades_q1,council.x)
###Change column name to make it match with other data sets
colnames (q1_stats) [1] <- "council"
###Create and add column for status update
q1_stats$dataSource <- "Q1"

### Read Grade 2 data
grades_q2 <- dbReadTable(getReal_2016db, "Q2_Absences")

###Pair down data
q2_stats <-select(grades_q2, council.x)

###Change column names
colnames (q2_stats) [1] <- "council"

### Add a column
q2_stats$dataSource <- "Q2"

###### Q3

grades_q3 <-dbReadTable(getReal_2016db, "Q3_Absences")

q3_stats <- grades_q3 %>%
    select(council.x) %>%
    mutate("dataSource"= "Q3") 


colnames (q3_stats) [1] <-"council"


#######Bind the grade data

q1_q2 <- rbind(q1_stats, q2_stats)

q1_q3 <-rbind(q1_q2, q3_stats)




###Findal addition to create data frame for status report




### Read the pre girl survey for reference down stream
girl_survey_dupes <-dbReadTable(getReal_2016db, "girl_pre_duplicates")

girl_survey_dupes$dataSource <-"Student"

girl_survey_dupes <- girl_survey_dupes %>%
    select(council, dataSource)


### Read the pre girl survey for reference down stream
parent_survey_dupes <-dbReadTable(getReal_2016db, "pre_parent_duplicate")

parent_survey_dupes$dataSource <-"Parent"

parent_survey_dupes <- parent_survey_dupes %>%
    select(council, dataSource)


survey_duplicates <- rbind(girl_survey_dupes, parent_survey_dupes)

### Read the pre girl survey for reference down stream

### Read Q1 dupes
q1_dupes <-dbReadTable(getReal_2016db, "Q1_duplicates")

q1_dupes <- select(q1_dupes, council)

### Add data source for q1. 
q1_dupes$dataSource <- "Q1"


### Read q2_dupes database
q2_dupes <-dbReadTable(getReal_2016db, "Q2_duplicates")

q2_dupes <-select(q2_dupes, council)

### add data source column
q2_dupes$dataSource <- "Q2"

### bind the data togehter. 
grades_dupes <- rbind(q1_dupes, q2_dupes)


### Reade the girl_pre_survey database for analysis. 
outcomes <- dbReadTable(getReal_2016db, "girl_pre")
###Select the variables of interest from the pre_survey
outcomes <- select(outcomes, girlCode, school, council, hr.avg, am.avg, ae.avg)

#### Read q1_reading data from database for analysis
q1_reading <-dbReadTable(getReal_2016db, "Q1_reading")

### Read q1_langarts data from database for analysis
q1_langarts <-dbReadTable(getReal_2016db,"Q1_lang")

###Read q1_absences data from database for analysis
q1_absences <-dbReadTable(getReal_2016db, "Q1_Absences")

###Read q2_absences data from database for analysis
q1_suspensions <- dbReadTable(getReal_2016db, "Q1_Suspensions")


###Read academic data from database for file explort
academic_data <- dbReadTable(getReal_2016db, "academic_data")



```


```{r survey_stats}

survey_status3 <- with(survey_status,table(dataSource))

survey_status3 <- addmargins(survey_status3)

pander(survey_status3)



```





###Survey Data Entry Status
```{r council_survey_status, echo = FALSE, eval=TRUE,}




survey_status2 <-with(survey_status,table(council, dataSource))

survey_status2 <- addmargins(survey_status2)

pander(survey_status2)


```


###Grade Data
```{r}
grade_data <-with(q1_q3,table(dataSource))

grade_data <- addmargins(grade_data)

pander(grade_data)

```


### Council Grade Data

```{r}

grade_data_c <-with(q1_q3,table(council, dataSource))

grade_data_c <- addmargins(grade_data_c)

pander(grade_data_c)


```





# Duplicate Date Entry Status
```{r echo= FALSE}
duplicates <- rbind(survey_duplicates, grades_dupes)

duplicates <- with(duplicates, table(council, dataSource))

duplicates <- addmargins(duplicates)

pander(duplicates)

```










